spring.application.name=Tailoring
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=pardhu
spring.datasource.password=513
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update